openapi: 3.0.0
info:
  title: Url Shortner
  version: 1.0.0
servers:
  - url: https://url-shortener-b4xw.onrender.com
paths:
  /shorten:
    post:
      tags:
        - default
      summary: Create Link
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                long_url: >-
                  https://portal.pixpay.ng/Payments/FeeReceipt?transref=FLW-4541-20220110-608759
                custom_alias: ''
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Sat, 08 Jul 2023 23:17:48 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            CF-Ray:
              schema:
                type: string
                example: 7e3c0aee5f3c0b47-AMS
            CF-Cache-Status:
              schema:
                type: string
                example: DYNAMIC
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            x-render-origin-server:
              schema:
                type: string
                example: Render
            Set-Cookie:
              schema:
                type: string
                example: >-
                  __cf_bm=a63ARYxlqPamXhYz9xc8tK6Ox9fa_D7GCcieVaC5fYk-1688858268-0-AeNTKFJ0wjMdyyHa+f0bR2OiMrVdPt8jDAA9XJwi53WiOUIfEZLq5x7Vdm8uDfBd5zKSugQwvV6KE+W/kHghfiQ=;
                  path=/; expires=Sat, 08-Jul-23 23:47:48 GMT;
                  domain=.onrender.com; HttpOnly; Secure; SameSite=None
            Server:
              schema:
                type: string
                example: cloudflare
            Content-Encoding:
              schema:
                type: string
                example: br
            alt-svc:
              schema:
                type: string
                example: h3=":443"; ma=86400
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  id: 2b2df8b4-5914-4216-b04e-a48e4bfd70c9
                  long_url: >-
                    https://portal.pixpay.ng/Payments/FeeReceipt?transref=FLW-4541-20220110-608759
                  short_url: https://url-shortener-b4xw.onrender.com/s/CsIUY
                  qr_code_url: https://url-shortener-b4xw.onrender.com/static/TNrvf.png
                  custom_alias: CsIUY
                  clicks: 0
                  last_access: ''
                  created_at: '2023-07-08T23:17:48.00876883Z'
                  updated_at: '2023-07-08T23:17:48.00876888Z'
                qr_code_url: https://url-shortener-b4xw.onrender.com/static/TNrvf.png
  /shorten/{alias}/stats:
    get:
      tags:
        - default
      summary: Get Page Analytics
      parameters:
        - name: alias
          in: path
          schema:
            type: string
          required: true
          example: sKrcu
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Sat, 08 Jul 2023 23:24:27 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            CF-Ray:
              schema:
                type: string
                example: 7e3c14acec2c0b47-AMS
            CF-Cache-Status:
              schema:
                type: string
                example: DYNAMIC
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            x-render-origin-server:
              schema:
                type: string
                example: Render
            Set-Cookie:
              schema:
                type: string
                example: >-
                  __cf_bm=4BIuOuAg1UhIKg7d5uV1jGYqWzO8QqH3hZ5LVraFDHA-1688858667-0-AXEiMtTz1MEWlqP08KtABQNvjITrICy3qqxxa6GR3ux1nLDyIpj+KmP5bSGV4pPCWGWZTmzbCKcXcR5sj8NQpnk=;
                  path=/; expires=Sat, 08-Jul-23 23:54:27 GMT;
                  domain=.onrender.com; HttpOnly; Secure; SameSite=None
            Server:
              schema:
                type: string
                example: cloudflare
            Content-Encoding:
              schema:
                type: string
                example: br
            alt-svc:
              schema:
                type: string
                example: h3=":443"; ma=86400
          content:
            application/json:
              schema:
                type: object
              example:
                originalURL: >-
                  https://portal.pixpay.ng/Payments/FeeReceipt?transref=FLW-4541-20220110-608759
                qrCodeURL: https://url-shortener-b4xw.onrender.com/static/bUHMA.png
                shortenedURL: https://url-shortener-b4xw.onrender.com/s/sKrcu
                visitCount: 3
  /s/sKrcu:
    get:
      tags:
        - default
      summary: Get Page Redirect
      responses:
        '200':
          description: OK
          headers:
            Cache-Control:
              schema:
                type: string
                example: private
            Content-Type:
              schema:
                type: string
                example: text/html; charset=utf-8
            Content-Encoding:
              schema:
                type: string
                example: br
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Server:
              schema:
                type: number
                example: Microsoft-IIS/10.0
            X-AspNet-Version:
              schema:
                type: number
                example: 4.0.30319
            X-Powered-By:
              schema:
                type: string
                example: ASP.NET
            Date:
              schema:
                type: string
                example: Sat, 08 Jul 2023 23:16:21 GMT
            Content-Length:
              schema:
                type: integer
                example: '1750'
          content:
            text/plain:
              schema:
                type: string
              example: "\r\n\r\n\n<!doctype html><html><head><link href=\"/Content/Images/favicon.png\" rel=\"icon\"><link href=\"/Content/Images/favicon.png\" rel=\"apple-touch-icon\"><title>School Fees Receipt</title><style type='text/css'>\r\n            body, html {\r\n            }\r\n            body {\r\n                color: black;\r\n                /*display: table;*/\r\n                font-family: Georgia, serif;\r\n                font-size: 24px;\r\n                text-align: center;\r\n\r\n            }\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n            .d-flex {\r\n                display: flex;\r\n            }\r\n\r\n            .px-3 {\r\n                padding-left: 1rem;\r\n                padding-right: 1rem;\r\n                margin-top: auto\r\n            }\r\n\r\n        \r\n            .justify-content-center {\r\n                justify-content: center;\r\n            }\r\n\r\n            .align-items-center {\r\n                align-items: center;\r\n            }\r\n            .container {\r\n                border: 1px solid black;\r\n                width: 500px;\r\n                height: ;\r\n                display: table-cell;\r\n                vertical-align: middle;\r\n                background-image: url(\"rpc.jpg\");\r\n                background-position: center;\r\n                background-size: cover;\r\n                margin-left: auto;\r\n                margin-right: auto;\r\n\r\n            }\r\n            .grid-container {\r\n                display: grid;\r\n                grid-template-columns: auto auto auto;\r\n                \r\n\r\n            }\r\n\r\n            .grid-item{\r\n                justify-content: space-between;\r\n                padding:20px;\r\n            }\r\n            .header-text {\r\n                color: black;\r\n                font-family: 'LEMON MILK';\r\n                font-size: 15px;\r\n                padding-top: 20px;\r\n            }\r\n\t\t\t.fee-topic {\r\n                color: black;\r\n                font-family: 'poppins';\r\n                font-size: 15px;\r\n                padding: 20px;\r\n            }\r\n\r\n            .ctc{\r\n                color: #de1313;\r\n                font-family:'Certificate';\r\n                font-size: 40px;\r\n                margin: 20px;\r\n            }\r\n            .assignment {\r\n                margin: 20px;\r\n                font-size: 13px;\r\n                font-family: 'Rage Italic';\r\n                \r\n            }\r\n            .person {\r\n                border-bottom: 2px solid black;\r\n                font-size: 32px;\r\n                font-style: italic;\r\n                margin: 20px auto;\r\n                width: 400px;\r\n            }\r\n            .reason {\r\n                margin: 20px;\r\n            }\r\n            h2 {\r\n                  color: #000000;\r\n                   position: relative;\r\n                     padding-left: -20px;\r\n                    font-weight: 400;\r\n                }\r\n                    \r\n                    h2:after {\r\n                    position: absolute;\r\n                    content: \"\";\r\n                    height: 2px;\r\n                    background-color: #242424;\r\n                    margin-left: 15px;\r\n                    top: 50%;\r\n            }\r\n\t\t\t.student-info{\r\n\t\t\talign-content:center;\r\n\t\t\t}\r\n        </style><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script type=\"text/javascript\">\r\n            function printSection(el){\r\n                var getFullContent = document.body.innerHTML;\r\n                var printsection = document.getElementById(el).innerHTML;\r\n                document.body.innerHTML = printsection;\r\n                window.print();\r\n                document.body.innerHTML = getFullContent;\r\n            }\r\n        </script></head><body><button type=\"button\" onclick=\"printSection('receipt')\">print</button><button type=\"button\" onclick=\"window.close()\">Close</button><div><div class=\"d-flex px-3\"><div class=\"container\" id=\"receipt\"><div class=\"header-text\"><b>St. Patrick&#39;s College Emene Enugu</b><br><div class=\"assignment\" style=\"margin-top:5px;\">Emene Enugu\r\n\t\t\t<br><b>stpatrickcollege1960@gmail.com , 08097286923</b></div></div><div class=\"grid-container\"><div class=\"grid-item\" style=\"width:30px; height: 30px;; margin-left:20px; margin-top:20px;z-index: 2; \"></div><div class=\"grid-item\"><img src=\"/Content/Images/Logos/schoolLogo-25.jpeg\" style=\"height:80px; position: absolute; z-index: 2; margin-top:-20px;\" alt=\"School LOGO\"></div><div class=\"grid-item\" style=\"width:30px; height: 30px; margin-left:120px; margin-top:0px;z-index: 2; \"><img id=\"imageQRCode\" src=\"../Content/Temp/qrcode_563265063.jpg\" /></div>\r\n                \r\n            </div><div class=\"fee-topic\" style=\"margin-top:-10px;\"><b>SCHOOL FEES PAYMENT RECEIPT</b></div><div class=\"student-info assignment\" style=\"margin-top:-5px;\"><table align=\"center\"><tr><td>Name Of Student:</td><td style=\"border: solid 1px black; width: 50%;\">AGU MUNACHI PROSPER</td></tr><tr><td>Admission Number:</td><td style=\"border: solid 1px black; width: 50%;\">SPACO193322</td></tr><tr><td>Class:</td><td style=\"border: solid 1px black; width: 50%;\">SS 2</td></tr><tr><td>Transaction Ref:</td><td style=\"border: solid 1px black; width: 50%;\">FLW-4541-20220110-608759</td></tr><tr><td>Transaction ID:</td><td style=\"border: solid 1px black; width: 50%;\">563265063</td></tr><tr><td>Amount Paid:</td><td style=\"border: solid 1px black; width: 50%;\">&#x20A6;60,000.00</td></tr><tr><td>Date Of Payment:</td><td style=\"border: solid 1px black; width: 50%;\">Monday, January 10, 2022</td></tr><tr><td>Outstanding Fee:</td><td style=\"border: solid 1px black; width: 50%;\">0.00</td></tr>\r\n</table><div class=\"fee-topic\" style=\"margin-top: -10px;\"><b>Payment Analysis</b></div><style>\r\ntable {\r\n  font-family: arial, sans-serif;\r\n  border-collapse: collapse;\r\n  width: 100%;\r\n  margin-top:-10px;\r\n}\r\n\r\ntd, th {\r\n  border: 1px solid #dddddd;\r\n  text-align: left;\r\n  padding: 8px;\r\n}\r\n\r\ntr:nth-child(even) {\r\n  background-color: #dddddd;\r\n}\r\n</style><table><tr><th>No.</th><th>Term/Session</th><th>Class</th><th>Description</th><th>Amount</th></tr><tr><td>1</td><td>2nd term 2021/2022</td><td>SS 2</td><td>School Fees</td><td>&#x20A6;53,000.00</td></tr><tr><td>2</td><td>2nd term 2021/2022</td><td>SS 2</td><td>BIble Diary 2022</td><td>&#x20A6;3,000.00</td></tr><tr><td>3</td><td>2nd term 2021/2022</td><td>SS 2</td><td>Feast Levy</td><td>&#x20A6;2,000.00</td></tr><tr><td>4</td><td>2nd term 2021/2022</td><td>SS 2</td><td>Magazine</td><td>&#x20A6;2,000.00</td></tr>\r\n</table>\r\n\r\n            \r\n            \r\n           </div>\r\n        \r\n        </div>\r\n\t\t</div>\r\n\t\t</div>\r\n    </body>\r\n</html>\r\n"
